In [8]:
import pandas as pd
import sklearn as sns
df=pd.read_csv('Heart.csv')
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [18]:
df=df.drop('Unnamed: 0',axis=1)
df

KeyError: "['Unnamed: 0'] not found in axis"

In [86]:
df.shape

(303, 14)

In [87]:
df.isnull()      # whole chart

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [88]:
n=df.isnull().sum()        # isnull sum from each column
n

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         2
AHD          0
dtype: int64

In [89]:
df.dtypes

Age            int64
Sex            int64
ChestPain     object
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal          object
AHD           object
dtype: object

In [90]:
df['Age'].min()            # minimun age from df

29

In [91]:
df['Age'].mean()           # mean of age

54.43894389438944

In [92]:
(df==0).sum()               #count zeros

Age            0
Sex           97
ChestPain      0
RestBP         0
Chol           0
Fbs          258
RestECG      151
MaxHR          0
ExAng        204
Oldpeak       99
Slope          0
Ca           176
Thal           0
AHD            0
dtype: int64

In [96]:
dff=df.drop('AHD',axis=1)
dff

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal

In [99]:
sevenFive=dff.sample(frac=0.75)           #divide into 75%
sevenFive

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
21,22,58,0,typical,150,283,1,2,162,0,1.0,1,0.0,normal
216,217,46,0,nontypical,105,204,0,0,172,0,0.0,1,0.0,normal
89,90,51,0,nonanginal,130,256,0,2,149,0,0.5,1,0.0,normal
220,221,41,0,nonanginal,112,268,0,2,172,1,0.0,1,0.0,normal
104,105,49,1,nonanginal,120,188,0,0,139,0,2.0,2,3.0,reversable
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16,17,48,1,nontypical,110,229,0,0,168,0,1.0,3,0.0,reversable
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable
81,82,53,0,asymptomatic,130,264,0,2,143,0,0.4,2,0.0,normal
173,174,62,0,asymptomatic,140,394,0,2,157,0,1.2,2,0.0,normal
203,204,64,0,nonanginal,140,313,0,0,133,0,0.2,1,0.0,reversable

In [76]:
twoFive=df.drop(sevenFive.index)
twoFive

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal
5,56,1,nontypical,120,236,0,0,178,0,0.8,1,0.0,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...
280,57,1,asymptomatic,110,335,0,0,143,1,3.0,2,1.0,reversable
283,35,1,nontypical,122,192,0,0,174,0,0.0,1,0.0,normal
293,63,1,asymptomatic,140,187,0,2,144,1,4.0,1,2.0,reversable
296,59,1,asymptomatic,164,176,1,2,90,0,1.0,2,2.0,fixed
297,57,0,asymptomatic,140,241,0,0,123,1,0.2,2,0.0,reversable

In [77]:
fiveCol=df[['Age','Sex','ChestPain','RestBP','Chol']]
fiveCol

     Age  Sex     ChestPain  RestBP  Chol
0     63    1       typical     145   233
1     67    1  asymptomatic     160   286
2     67    1  asymptomatic     120   229
3     37    1    nonanginal     130   250
4     41    0    nontypical     130   204
..   ...  ...           ...     ...   ...
298   45    1       typical     110   264
299   68    1  asymptomatic     144   193
300   57    1  asymptomatic     130   131
301   57    0    nontypical     130   236
302   38    1    nonanginal     138   175

[303 rows x 5 columns]

In [2]:
x=df

NameError: name 'df' is not defined

In [98]:
y=df['AHD']

In [1]:
y=y.map({'False':0,'True':1})

NameError: name 'y' is not defined

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=10)

In [55]:
x_train

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
286,58,0,asymptomatic,170,225,1,2,146,1,2.8,2,2.0,fixed,Yes
102,57,0,asymptomatic,128,303,0,2,159,0,0.0,1,1.0,normal,No
242,49,0,asymptomatic,130,269,0,0,163,0,0.0,1,0.0,normal,No
65,60,1,asymptomatic,145,282,0,2,142,1,2.8,2,2.0,reversable,Yes
35,42,1,asymptomatic,140,226,0,0,178,0,0.0,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
156,51,1,asymptomatic,140,299,0,0,173,1,1.6,1,0.0,reversable,Yes
123,55,1,asymptomatic,140,217,0,0,111,1,5.6,3,0.0,reversable,Yes
15,57,1,nonanginal,150,168,0,0,174,0,1.6,1,0.0,normal,No
125,45,0,nontypical,130,234,0,2,175,0,0.6,2,0.0,normal,No
265,42,1,asymptomatic,136,315,0,0,125,1,1.8,2,0.0,fixed,Yes

In [56]:
y_train

286    1
102    0
242    0
65     1
35     0
      ..
156    1
123    1
15     0
125    0
265    1
Name: AHD, Length: 242, dtype: int64

In [57]:
x_test

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
246,58,1,asymptomatic,100,234,0,0,156,0,0.1,1,1.0,reversable,Yes
183,59,1,typical,178,270,0,2,145,0,4.2,3,0.0,reversable,No
229,66,1,asymptomatic,112,212,0,2,132,1,0.1,1,1.0,normal,Yes
126,56,0,asymptomatic,200,288,1,2,133,1,4.0,3,2.0,reversable,Yes
184,60,0,asymptomatic,158,305,0,2,161,0,0.0,1,0.0,normal,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
277,39,0,nonanginal,138,220,0,0,152,0,0.0,2,0.0,normal,No
121,63,0,asymptomatic,150,407,0,2,154,0,4.0,2,3.0,reversable,Yes
187,66,1,nontypical,160,246,0,0,120,1,0.0,2,3.0,fixed,Yes
301,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
283,35,1,nontypical,122,192,0,0,174,0,0.0,1,0.0,normal,No

In [58]:
y_test

246    1
183    0
229    1
126    1
184    1
      ..
277    0
121    1
187    1
301    1
283    0
Name: AHD, Length: 61, dtype: int64